### PR TITLE
chore(deps) bump, all tests pass

### PR DESCRIPTION
**Pull request by peterennis**
capture423

### CODE REVIEW

**Comment by peterennis** [comment]
Looks like filesize was an artifact of yarn.
Unused files moved to old folder.
Tests pass.
A new package release could be made and I expect it should not show a dep for filesize (GPL).
Fixes https://github.com/notoriousb1t/polymorph/issues/14
capture424
capture425
capture426

**Comment by notoriousb1t** [comment]
Thank you for putting this together.  Instead of renaming yarn, we should delete it altogether.  The history of the file will be kept in source control so I am not particularly worried about it.

The tsconfig.es2015.json and tsconfig.node.json are still used in this project, so we should not be modifying them.  Can you rename them back to their old location?  

Otherwise, this LGTM 👍

**Comment by peterennis** [comment]
fix() remove yarn.lock and restore tsconfig options
All tests pass
Version is bumped
I can test a new release to confirm GPL dep removal
capture427

**Comment by notoriousb1t** [comment]
Thank you for the contribution 👍

**Pull request merged**
