### PR TITLE
bugfix(es2015) Drop es2015 version

### LINKED ISSUE #40: Webpack grabbing es2015 version instead – fails to run on older browser
Hello!

I'm trying to import this into a project that supports only up to es5 (to support ie11 🤷🏻‍♂️) but it is throwing errors because it pulls in the es2015 version of the lib.

Is there a way to pull in an es5 compatible version, or to transpile a version to es5?

### PR DESCRIPTION
**Pull request by ericbf**
This commit drops the es2015 as builders sometimes pick the wrong one, making the package unusable in some situations. Fixes #40.

Just putting this out there as you said you were thinking about it @notoriousb1t

### CODE REVIEW

**Comment by notoriousb1t** [comment]
Thank you for taking care of this! 😄 Since this removes the es2015 file patch from the published npm version which makes this a major version and it is below version 1, I am going to make a few other changes and publish this as a major in a day or so.

**Comment by ericbf** [comment]
> I am going to make a few other changes and publish this as a major in a day or so.

Any update on this major release?

**Comment by notoriousb1t** [comment]
I just published 1.0.0.  Please take a look and let me know if that works.

**Comment by ericbf** [comment]
Looks to be working well!

**Pull request merged**
